<html><head><title>Online Universal Solver</title></head>
<body>
<?php
include ('siteHeader.php');
include ('zzStatCounter.php');
?>
<h2>Online Universal Solver</h2><br>
A little widget brought to you by PotatoEngineer, a.k.a. Cor.<p>

Enter the letters you're seeking:
<input type="text" size="26" id="targetLetters" />
<input type="button" value="Find Items!" onclick="findItems()" />
<br>Results must have at least one of each input letter: <input type="checkbox" id='allLetters' />
<br>"General Value" means the total value of all the letters of the word, weighted by their frequency.
<p><span id="resultdiv"></span>
<p>Also: get a random item! <input type="button" value="Mystery!" onclick="randomWord()" /> <input type="text" size="30" id="randomWordText" />

<script type="text/javascript">
//Bah.  Classes in Javascript.  Kinda ugly-looking, if you ask me.  Reasonably elegant to use, yes, but their definitions are pure ugly.
wordScore.prototype._word;
wordScore.prototype._scores;
wordScore.prototype._value;
wordScore.prototype.getScores=function(){return this._scores;}
wordScore.prototype.getWord=function(){return this._word;}
wordScore.prototype.addScore=function (newScore) {this._scores.push(newScore);}
wordScore.prototype.calcScore=function () {
	var count=0;
	for (var m=0;m<this._scores.length;m++) {
		count+=this._scores[m][1];
	}
	//GM_log('wordScore in comparison:'+count);
	return count;
}
wordScore.prototype.getScore=function(letter) {
	for (var n=0;n<this._scores.length;n++) {
		if (this._scores[n][0]==letter) return this._scores[1];
	}
	return 0;
}
function wordScore (word) {
	this._word=word;
	this._scores=new Array();
	this._value=-1;
}
var letterValue={"a":8.167,
"b":1.492,
"c":2.782,
"d":4.253,
"e":12.702,
"f":2.228,
"g":2.015,
"h":6.094,
"i":6.966,
"j":0.153,
"k":0.772,
"l":4.025,
"m":2.406,
"n":6.749,
"o":7.507,
"p":1.929,
"q":0.095,
"r":5.987,
"s":6.327,
"t":9.056,
"u":2.758,
"v":0.978,
"w":2.36,
"x":0.15,
"y":1.974,
"z":0.074};
wordScore.prototype.getValue =function(){
	if (this._value==-1) {
		var value=0;
		for (var o=0;o<this._word.length;o++) {
			if (/^[a-z]$/.test(this._word[o].toLowerCase())) {
				value+=letterValue[this._word[o].toLowerCase()];
			}
		}
		this._value=value;
	}
	return this._value;
}

//CODE EXECUTED ON EVERY PAGE LOAD
var allWords=loadData();

function randomWord() {
	var resultBox=document.getElementById('randomWordText');
	resultBox.value=getRandomWord();
}

function getRandomWord() {
	var i = Math.round(allWords.length*Math.random());
	return allWords[i];
}

function findItems() {
	var inputString=document.getElementById('targetLetters').value;

	// first, sanitize the input string.  I only want the alphabetical letters.
	inputString=inputString.toLowerCase();
	inputString.replace(/[^a-z]/g,'');
	
	// now, get the UNIQUE letters from the input string.  Have you noticed that I'm assuming the user is a complete and utter idiot?  Am I wasting my time?  Possibly, but now, it's GUARANTEED!  ....for what it's worth.  I'm tired, and I'm adding features for the hell of it before I even make the script WORK.  I think there's something fundamentally wrong with programmers.  :)
	inputString=inputString.split('');
	inputString.sort();
	inputString=inputString.join('');
	var letters= new Array();
	var j=-1;
	for (var i=0;i<inputString.length;i++) {
		// if I have my rules right, when j is -1, it should short-circuit and never test letters [-1]
		if (letters.length==0 || letters[j]!=inputString[i]) {
			letters.push(inputString[i]);
			j++;
		}
	}
	
	var valuableWords=new Array();
	for (var i=0;i<allWords.length;i++) {
		var ws = new wordScore(allWords[i]);
		// there is probably a better way to do this.  Ah, well, O(N^3), here we come!
		for (var k=0;k<letters.length;k++) {
			var foundLetter=false;
			var letterAndScore=false;
			for (var j=0;j<allWords[i].length;j++) {
				if (allWords[i][j].toLowerCase()==letters[k]) {
					//GM_log('found match! '+word[j]+' and '+letters[k]+' in '+word);
					if (!foundLetter) {
						letterAndScore=new Array(letters[k],1);
						foundLetter=true;
					}
					else letterAndScore[1]+=1;
				}
			}
			if (letterAndScore) ws.addScore(letterAndScore);
		}
		if (ws.calcScore()) {
			valuableWords.push(ws);
		}
		else delete ws;
	}
	
	// if they want their words to have one of each letter, that's what they get.
	if (document.getElementById('allLetters').checked) {
		for (var i=0;i<valuableWords.length;i++) {
			for (var j=0;j<letters.length;j++) {
				if (valuableWords[i].getScore(letters[j])==0) {
					valuableWords.splice(i,1);
					i--;
					break;
				}
			}
		}
	}
	
	valuableWords.sort(function (a,b) {var scoreDiff=b.calcScore()-a.calcScore(); if (scoreDiff==0) return b.getValue()-a.getValue(); return scoreDiff;});
	
	var output='<br><table border="0" cellpadding="3">';
	for (var i=0;i<valuableWords.length;i++) {
		var scoreArray=valuableWords[i].getScores();
		output+='<tr><td>'+valuableWords[i].getWord()+' </td>';
		for (var j=0;j<scoreArray.length;j++) {
			output+='<td>'+scoreArray[j][0]+': '+scoreArray[j][1]+' </td>';
		}
		for (var k=j;k<letters.length;k++) {
			output+='<td>&nbsp</td>';
		}
		output+='<td>General Value: '+Math.round(valuableWords[i].getValue())+'</td>';
		output+='</tr>';
	}
	output+='</table>';
	document.getElementById('resultdiv').innerHTML=output;
}

// poor, poor Cursed Rainbow Glass Vorpal Sword of You Spin Me Right Round.... you are no longer.
function loadData() {
	return new Array (
"2 Iron",
"3 Iron",
"4 Iron",
"5 Iron",
"6 Iron",
"7 Iron",
"8 Iron",
"9 Iron",
"A",
"A Bomb in a Ball",
"A bit put-out Bow",
"Abcdefghijklmnopqrstuvwxy",
"Accordion",
"Acle",
"After-Dinner Mint",
"Air Bow",
"Air Catana",
"Air Knife",
"Air Ship",
"Air Stone",
"Air Sword",
"Air Sword2",
"Air Talisman",
"Air Wand",
"Air Wand2",
"Air Wand3",
"Alchemy Spell",
"Align Air Spell",
"Align All to Air Spell",
"Align All to Earth Spell",
"Align All to Fire Spell",
"Align All to Water Spell",
"Align Area to Air Spell",
"Align Area to Earth Spell",
"Align Area to Fire Spell",
"Align Area to Water Spell",
"Align Earth Spell",
"Align Fire Spell",
"Align Water Spell",
"All or Nothing Spell",
"Amok Spell",
"Amp",
"Amulet Of Endor",
"Angry Bow",
"Annoyance",
"Annoyed Bow",
"Annoying Plastic Thing",
"Antenna",
"Anti-Hista",
"Anvil",
"Apron",
"Archers Charm Spell",
"Archers Luck Spell",
"Arena Talisman",
"Army Boot",
"Arrow",
"Astral Plain Spell",
"Astrolabe",
"Augers Aim Spell",
"Aventail",
"B",
"B.B. Gun",
"BB",
"BLT Sandwich",
"Bacon Sandwich",
"Badge",
"Bag (Kit for Beginners)",
"Bag of Cocoa Powder",
"Bag of Coffee Beans",
"Bag of Flour",
"Bag of Grain Mash",
"Bag of Ground Coffee",
"Bag of Roasted Coffee Beans",
"Bag of Walnuts",
"Ball Invitation",
"Ball Mill",
"Ball of Wool",
"Barbelith Talisman",
"Bascinet",
"Bashing Stuff Spell",
"Basket",
"Basket of Crushed Plums",
"Basket of Dried Figs",
"Basket of Dried Plums",
"Basket of Figs",
"Basket of Plums",
"Bauhaus T-Shirt",
"Bebe Goggles",
"Become Air Spell",
"Become Earth Spell",
"Become Fire Spell",
"Become Water Spell",
"Beef Steak",
"Bent Pin",
"Big Blue India-Rubber Ball",
"Big Machete",
"Big Map",
"Big Piece of Chalk",
"Big Red India-Rubber Ball",
"Bilbo Cocktail",
"Billy Can",
"Bind Elemental Spell",
"Bind Spirit Spell",
"Bit of Bronze",
"Bit of Copper",
"Bit of Gold",
"Bit of Iron",
"Bit of Lead",
"Bit of Misril",
"Bit of Molten Glass",
"Bit of Parchment",
"Bit of Silver",
"Black Eye Liners",
"Black Nail Polish",
"Blacksmith's Tongs",
"Blank Talisman",
"Blessed Sword",
"Bling Bling",
"Bling of Fire",
"Bling of Ice",
"Bloody Mary",
"Blowtorch",
"Blubber",
"Blue Flower",
"Blue Pill",
"Blue Ribbon",
"Bo Staff",
"Bone",
"Boniface Potion",
"Book",
"Book",
"Book",
"Bottle of Anisette",
"Bottle of Brandy",
"Bottle of Coconut Milk",
"Bottle of Creme de Cacao",
"Bottle of Creme de Menthe",
"Bottle of Dragon Fruit Juice",
"Bottle of Gin",
"Bottle of Ginger Wine",
"Bottle of Grenadine",
"Bottle of Grog",
"Bottle of Herb Liqueur",
"Bottle of Kahlua",
"Bottle of Lemon Juice",
"Bottle of Lime Juice",
"Bottle of Olive Oil",
"Bottle of Orange Juice",
"Bottle of Pepper Sauce",
"Bottle of Pineapple Juice",
"Bottle of Romulan Ale",
"Bottle of Rum",
"Bottle of Saurian Brandy",
"Bottle of Sloe Gin",
"Bottle of Sparkling Water",
"Bottle of Sparkling Wine",
"Bottle of Tequila",
"Bottle of Tomato Juice",
"Bottle of Tonic Water",
"Bottle of Triple Sec",
"Bottle of Vermouth",
"Bottle of Vinegar",
"Bottle of Vodka",
"Bottle of Whisky",
"Bow",
"Bowl of Irish Stew",
"Bowling Ball",
"Bowling Permit",
"Box of Parts",
"Brak Potion",
"Brand New Dog Bot",
"Brand New Electric Sheep",
"Brandy Alexander",
"Brave Star",
"Breakfast Bar",
"Breakfast Club",
"Breakfast Club Sandwich",
"Brighthelm Rock",
"Broad Sword",
"Broken Phaser",
"Bronze Greave",
"Bronze Nail",
"Bronze Ore",
"Bronze Scale Armour",
"Bronze Vambrace",
"Brown Cow",
"Bucket",
"Bucky Ball",
"Bun",
"Bunch of Grapes",
"C",
"Cactus",
"Calendar",
"Can of Lager",
"Can of Red Bull",
"Can of Worms",
"Can of Wyrms",
"Candle",
"Candle Stub",
"Cannon Ball",
"Caravel (in a bottle)",
"Caravel with hole (in a bottle)",
"Carbon",
"Card (Guild Treasury Card)",
"Card: Death",
"Card: Judgement",
"Card: Justice",
"Card: Strength",
"Card: Temperance",
"Card: The Chariot",
"Card: The Devil",
"Card: The Emperor",
"Card: The Empress",
"Card: The Fool",
"Card: The Hanged Man",
"Card: The Hermit",
"Card: The Hierophant",
"Card: The High Priestess",
"Card: The Lovers",
"Card: The Magician",
"Card: The Moon",
"Card: The Star",
"Card: The Sun",
"Card: The Tower",
"Card: The Wheel of Fortune",
"Card: The World",
"Carrot",
"Catana",
"Cattle Prod",
"Chain",
"Champagne Cocktail",
"Chausse",
"Cherry Bomb",
"Chillwell Potion",
"Chocolate Bombe",
"Christmas Cracker",
"Cigar",
"Clean Bandage",
"Clear Spell",
"Climbing Gear",
"Clinic Invite",
"Cloak of Invisibility",
"Clock of Invisibility",
"Clove of Garlic",
"Club 18-30",
"Cluster Bomb",
"Cockroach",
"Cocktail Shaker",
"Cocktail Stick",
"Cocoa Bean",
"Coconut",
"Cod",
"Cod Liver Oil",
"Cod Piece",
"Cold Chisel",
"Coloured Scarf",
"Columbine",
"Compass",
"Compressed Air Spell",
"Compressed Earth Spell",
"Compressed Fire Spell",
"Compressed Water Spell",
"Consonant",
"Contract Palantir",
"Cool Disguise",
"Copper Axe",
"Copper Axe (Treeman bane)",
"Copper Nail",
"Copper Ore",
"Copy of 'All the Things She Said'",
"Copy of 'Atomic'",
"Copy of 'Beautiful'",
"Copy of 'Believe'",
"Copy of 'Dancing Queen'",
"Copy of 'Diamonds Are Forever'",
"Copy of 'Diamonds Are a Girl's Best Friend'",
"Copy of 'Dirrty'",
"Copy of 'Express Yourself'",
"Copy of 'G.A.Y.'",
"Copy of 'Gimme! Gimme! Gimme! (A Man After Midnight)'",
"Copy of 'Girls Just Want to Have Fun'",
"Copy of 'Go West'",
"Copy of 'I Will Survive'",
"Copy of 'I'm Coming Out'",
"Copy of 'I'm Still Standing'",
"Copy of 'It's Raining Men'",
"Copy of 'It's a Sin'",
"Copy of 'Lady Marmalade'",
"Copy of 'Like I Love You'",
"Copy of 'Love at First Sight'",
"Copy of 'Macho Man'",
"Copy of 'Mamma Mia'",
"Copy of 'Man! I Feel Like A Woman!'",
"Copy of 'Over the Rainbow'",
"Copy of 'Relax'",
"Copy of 'Strong Enough'",
"Copy of 'Vogue'",
"Copy of 'Where Is My Man'",
"Copy of 'Y.M.C.A.'",
"Copy of 'You Spin Me Round (Like a Record)'",
"Copy of 'Your Disco Needs You'",
"Copy of Battlefield Earth",
"Copy of Between Planets",
"Copy of Beyond This Horizon",
"Copy of Citizen of the Galaxy",
"Copy of Double Star",
"Copy of Farmer in the Sky",
"Copy of Farnham's Freehold",
"Copy of Friday",
"Copy of Glory Road",
"Copy of Have Space Suit - Will Travel",
"Copy of I Will Fear No Evil",
"Copy of Job: A Comedy of Justice",
"Copy of Methuselah's Children",
"Copy of Podkayne of Mars",
"Copy of Red Planet",
"Copy of Rocket Ship Galileo",
"Copy of Sixth Column",
"Copy of Space Cadet",
"Copy of Starman Jones",
"Copy of Starship Troopers",
"Copy of Stranger in a Strange Land",
"Copy of The Cat Who Walks Through Walls",
"Copy of The Citizen",
"Copy of The Door into Summer",
"Copy of The Moon Is a Harsh Mistress",
"Copy of The Number of the Beast",
"Copy of The Puppet Masters",
"Copy of The Rolling Stones",
"Copy of The Star Beast",
"Copy of Time Enough for Love",
"Copy of Time for the Stars",
"Copy of To Sail Beyond the Sunset",
"Copy of Tunnel in the Sky",
"Copy of Variable Star",
"Corpse of Yes",
"Cricket Ball",
"Crispy Shredded Duck Bit",
"Critical Healing Spell",
"Crocodile Dundee Cake",
"Crocodile Scale",
"Cross Bow",
"Crow Bow",
"Cruel Blade",
"Cruel Death Wand",
"Crumhorn",
"Crushed Bunch of Grapes",
"Cucumber",
"Cucumber Sandwich",
"Cucumber Slice",
"Cup of Tea",
"Cursed Rainbow Glass Vorpal Blade Of You Spin Me Right Round",
"Cursed Sword",
"D",
"D10",
"D12",
"D20",
"D4",
"D6",
"D8",
"Daemonic Chain Saw",
"Daemonic Chainsaw Nunchucks",
"Daemonic Dagger",
"Daemonic Great Sword",
"Daemonic Knife",
"Daemonic Letter Opener",
"Daemonic Sword",
"Daily Mail",
"Daiquiri",
"Dark Bow",
"Dark Catana",
"Dark Knife x 2",
"Dark Stone",
"Dark Sword",
"Dark Sword2",
"Dark Talisman x 2",
"Dark Wand",
"Dark Wand2",
"Dark Wand3",
"Darken Spell",
"Dawn Horn",
"Death Wand",
"Deck",
"Devilishly Clever Trap",
"Dharma Potion",
"Diamond",
"Diamond Bling",
"Diamond Team Ring (Team Small Sand Worm)",
"Dibs Wand",
"Didgeridoo",
"Dimmed Light Sabre",
"Disguise Kit",
"Dissolution Spell",
"Distaff",
"Dojo Talisman",
"Doom Wand",
"Dose of Antidote",
"Dose of Magic Powder",
"Double Crow Bow",
"Drag on-and-on Spell",
"Dragon Blood",
"Dragon Fruit",
"Dragon Spear",
"Dragon Stone",
"Dream Sword",
"Dry Martini",
"Dueling Sabre",
"Dull Catana",
"Dull Golden Sickle",
"Dull Knife",
"Dull Silver Catana",
"Dull Silver Knife",
"Dull Silver Sword",
"Dull Sword",
"Dundee Cake",
"Dung Egg",
"Duoacle",
"Dusk Tusk",
"E",
"ERROR(No type!)",
"Earth Bow",
"Earth Catana",
"Earth Knife",
"Earth Stone",
"Earth Sword",
"Earth Sword2",
"Earth Talisman",
"Earth Wand",
"Earth Wand2",
"Earth Wand3",
"Eel",
"Egg",
"Egg Nog",
"Eighth of the Moon",
"Elevator Orange Sorbet",
"Elf Arrow",
"Emerald Athame",
"Emerald Bling",
"Emerald Team Ring (Team Small Sand Worm)",
"Emergency Flare",
"Empty Book",
"Empty Bottle",
"Empty Cocktail Glass",
"Empty Jar",
"Empty Mug",
"Empty Pinhole Camera",
"Empty Vial",
"Enchant Air Sword Spell",
"Enchant Earth Sword Spell",
"Enchant Fire Sword Spell",
"Enchant Mud Spell",
"Enchant Silver Spell",
"Enchant Water Sword Spell",
"Enduring Strength Spell",
"Entangled Fleece",
"Erotic Cocktail",
"Exotic Cocktail",
"Eye Pod",
"F",
"F.L.A. T-Shirt",
"Fag",
"Fang",
"Fast Defence Spell",
"Feather",
"Feathered Bling",
"Fern",
"Ferret Egg",
"Ferry (in a bottle)",
"Fiddle",
"Field Glasses",
"File",
"Fire Bow",
"Fire Catana",
"Fire Cracker",
"Fire Knife",
"Fire Stone",
"Fire Sword",
"Fire Sword2",
"Fire Talisman",
"Fire Wand",
"Fire Wand2",
"Fire Wand3",
"Fire-Ball Spell",
"Fireworks",
"First Aid Spell",
"Fishing Net",
"Fishing Rod",
"Fistful of Almonds",
"Flake Shaker",
"Flash Gun",
"Flash Gun (Flat)",
"Fleece",
"Fleeting Strength Spell",
"Flipper",
"Flying Bacon Sandwich",
"Flying Fish",
"Foot Ball",
"Fork",
"Fortune Cookie",
"Fountain Pen",
"Four-Pack of Lager",
"Frankenwiener Spell",
"Frodo Cocktail",
"Front 242 T-Shirt",
"Fruit Cake",
"Fruit Cake (aging)",
"Full Defence Spell",
"Fungal Spray Spell",
"Fur Coat",
"Furious Bow",
"G",
"GPS",
"Gandalf Cocktail",
"Gas Bill",
"Gas Lantern",
"Gauntlet",
"Ghastly Bling",
"Gherkin",
"Giant Snowball",
"Gift Box",
"Gimlet",
"Gin and Tonic",
"Glass Sword",
"Glass of Absinthe",
"Glass of Polar Beer",
"Glass of Wine",
"Glowing Miners Hat",
"Glowing Moon Stone Bling",
"Glowing Night Club",
"Glowing Night Stick",
"Goat Hair",
"Goat Horn",
"Gold Bling",
"Gold Ore",
"Gold Rune",
"Golden Gun",
"Golden Sickle",
"Goldfish Egg",
"Gollum Cocktail",
"Gooey Palantir",
"Goose Egg",
"Gorgan-zola Sandwich",
"Gram of Fairy Dust",
"Gram of Spice",
"Grappling Hook",
"Grasshopper",
"Grenade",
"Grey Swan Deer",
"Gruff",
"Guide to Time and Space",
"Guild Comms Room Kit",
"Guild Decorator",
"Guild Locker",
"Guild Namer",
"Guild Permit",
"Guild Resignation Letter",
"Guild Store Kit",
"Guild Teleport Kit",
"Guild Temple Kit",
"Guild Ticket Office Kit",
"Guild Trading Post Kit",
"Guild Tunnel Kit",
"H",
"Haggis",
"Half of the Moon",
"Hammer",
"Hand Bell",
"Handful of Dough",
"Hard and Pointy Stick",
"Harmonica",
"Harpoon",
"Harpsichord",
"Harvey's Bristol Cream",
"Hat Hunter Spell",
"Hat Trick Spell",
"Haubergeon",
"Hauberk",
"Head of the Gorgan",
"Healing Bling",
"Hill Fort Permit",
"Hoe ov Destruction",
"Hop East Spell",
"Hop North Spell",
"Hop South Spell",
"Hop West Spell",
"Horizontal Bling",
"Hot Air Gun",
"Huge Fire Cracker",
"Human Heart",
"Human Liver",
"Humidor",
"Hurt 'em Lots Spell",
"Hurt 'em Spell",
"Hyper-Link",
"I",
"Ice Bow",
"Ice Catana",
"Ice Knife",
"Ice Pick",
"Ice Stone",
"Ice Sword",
"Ice Sword2",
"Ice Talisman",
"Ice Wand",
"Ice Wand2",
"Ice Wand3",
"Impending Kick Spell",
"Impending Slap Spell",
"Invisibility Spell",
"Iron Bling",
"Iron Hubbard",
"Iron Maiden",
"Iron Nail",
"Iron Ore",
"Iron Ring",
"J",
"Jar of Gas",
"Jar of Grape Jam",
"Jar of Plum Jam",
"Jewel of the Mountain King",
"Jumper",
"Jumper with holes",
"Jumper with many holes",
"K",
"Kelley Spell",
"Key (Duke Cor MDs Vault)",
"Killing Blow Spell",
"Kings Crest Talisman",
"Kipple",
"Kirk's Map",
"Kittin Egg",
"Kittin Kibble",
"Knife",
"Kraken Meat",
"Kraken Piece",
"L",
"Lambs Liver",
"Lance",
"Largo",
"Lava Solvent",
"Lead Ore",
"Leather Cuirass",
"Leather Glove",
"Leather Gorget",
"Leather Greave",
"Leather Jacket",
"Leather Vambrace",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Leech",
"Legolas Cocktail",
"Lemon",
"Lettuce",
"Lettuce Leaf",
"Light Wand",
"Limbo Talisman",
"Lime",
"Lion Fish",
"Loaf of Bread",
"Locate Spell",
"Long Bow",
"Lucky Strike",
"Lump Hammer",
"Lump of Beeswax",
"Lump of Cactus Pulp",
"Lump of Mashed Beans",
"Lump of Minced Beef",
"M",
"MOTD Spell",
"Machete",
"Magic Ball",
"Magic Bean",
"Magic Carpet",
"Magic Cookie",
"Magic Display Spell",
"Magic Egg",
"Magic Emerald",
"Magic Map",
"Magic Mining Permit",
"Magic Mud",
"Magic Opal",
"Magic Ruby",
"Magical Aura Spell",
"Mail On Sunday",
"Major Healing Bling",
"Major Healing Spell",
"Mall Talisman",
"Manhattan",
"Map",
"Map Spell",
"Map Spell Extreme",
"Map Spell Pro",
"Map of Bognor",
"Map of Brighthelm",
"Map of Earth City",
"Map of Fire City",
"Map of Harvey Hall",
"Map of Isle of Fright",
"Map of Water City",
"Map of Windy City",
"Map of the Castle",
"Map of the Festival",
"Map of the Forest",
"Map to K.O.T. Keep",
"Map to the Hermit",
"Map to the Shrines",
"Margherita",
"Marwell Talisman",
"May Ball",
"Mayfly Egg",
"Measure of Black Powder",
"Mercury Bling",
"Merz Bow",
"Midas Wand",
"Mincer",
"Miners Hat",
"Mini-K-A-M",
"Mining Laser",
"Mining Permit",
"Minor Healing Spell",
"Mint Julep",
"Minty Python Ice Cream",
"Mirror",
"Misril Bling",
"Misril Ore",
"Misril Skin Spell",
"Miss A Bit Less Spell",
"Mixed Salad",
"Mojito",
"Moon On A Stick",
"More-Compressed Air Spell",
"More-Compressed Earth Spell",
"More-Compressed Fire Spell",
"More-Compressed Water Spell",
"Morning Star",
"Mortar",
"Mud",
"Mug of Ale",
"Mug of Coffee (decaf)",
"Mug of Coffee (proper)",
"Mug of Ginger Beer",
"Mug of Hot Chocolate",
"Mule",
"Multicoloured Scarf",
"Murder Bow",
"Mushroom",
"Mysterious Envelope",
"Mystic Aim Spell",
"N",
"N'gann Potion",
"Needle",
"Neutral Bow",
"Neutral Catana",
"Neutral Knife",
"Neutral Stone",
"Neutral Sword",
"Neutral Sword2",
"Neutral Talisman",
"Neutral Wand",
"Neutral Wand2",
"Neutral Wand3",
"New Bag",
"New Cabinet",
"New Eye Pod",
"Nightingbreeze Spell",
"Nightinggale Spell",
"Nightinghurricane Spell",
"Nightingstorm Spell",
"Norse/English dictionary",
"North-East Tunnel Map",
"North-East Tunnel Talisman",
"North-West Tunnel Map",
"North-West Tunnel Talisman",
"Northern Rock",
"Nothing",
"Nuff",
"Nun Chucks",
"O",
"Oil",
"Oil Lantern",
"Old Bauhaus T-Shirt",
"Old Boot",
"Old F.L.A. T-Shirt",
"Old Ramones T-Shirt",
"Old Sex Pistols T-Shirt",
"Old Sisters of Mercy T-Shirt",
"Olive",
"Onion",
"Onion Ring",
"Onyx Bling",
"Ooh",
"Opal Bling",
"Opal Team Ring (Team Small Sand Worm)",
"Orange",
"P",
"Pair of Beer Goggles",
"Pair of Bunny Ears",
"Pair of Daedalus Wings",
"Pair of Dr. Martins",
"Pair of Ear Muffs",
"Pair of Firefly Trainers",
"Pair of Fishnets",
"Pair of Heavy Boots",
"Pair of Holey Fishnets",
"Pair of Holey Socks",
"Pair of Knitting Needles",
"Pair of Kraken Trainers",
"Pair of Magic Boots",
"Pair of Pointy Boots",
"Pair of Reading Glasses",
"Pair of Scissors",
"Pair of Shades",
"Pair of Snow Goggles",
"Pair of Snowshoes",
"Pair of Socks",
"Pair of Tongs",
"Pair of Wellys",
"Palantir-as-you-go",
"Parcel (Parcel for Cor)",
"Party Pack",
"Pearl",
"Pentacle",
"Perl",
"Pestle",
"Phaser",
"Phoen Ice",
"Phoenix Feather",
"Pickaxe",
"Pickle Slice",
"Picnic Basket",
"Piece of Ancient Wood",
"Piece of Buttered Toast",
"Piece of Cardboard",
"Piece of Chalk",
"Piece of Honeycomb",
"Piece of Jammy Toast",
"Piece of Leather",
"Piece of Mail",
"Piece of Mutton",
"Piece of Red Chalk",
"Piece of Soylent Green",
"Piece of Toast",
"Piece of Wood",
"Pin",
"Pina Colada",
"Pinch of Salt",
"Pineapple",
"Pinhole Camera",
"Pint of Blood",
"Pint of Cider and Black",
"Pint of Cream",
"Pint of Fairy Liquid",
"Pint of Goat's Milk",
"Pint of Milk",
"Pint of Sheep's Milk",
"Pizza",
"Pizza Slice",
"Plan for a Boat",
"Plan for a Caravel",
"Plan for a Ferry",
"Plan for a Raft",
"Plan for a Survey Vessel",
"Plan for an Air Ship",
"Plans for a Speed Boat",
"Planter's Punch",
"Plowshare",
"Plum Pie",
"Pocket Watch",
"Pointy Stick",
"Poison Apple Sorbet",
"Poison Dart",
"Pokey Stick",
"Pomegranate",
"Portion of Bangers and Mash",
"Portion of Chips",
"Portion of Mashed Potato",
"Possibility",
"Possible Sword",
"Pot of Kraken Klaw Koleslaw",
"Potato",
"Potion of Accuracy",
"Potion of Healing",
"Pouch of Magic Herb",
"Pound of Poop",
"Power Crystal",
"Primary Key",
"Proper Scarf",
"Pumpkin",
"Putter",
"Pwny Egg",
"Q",
"Quad-Crow Bow",
"Quadacle",
"Quarrel",
"Quarter of the Moon",
"Quiche",
"Quick Shield Spell",
"R",
"Rabbit Foot",
"Raft (in a bottle)",
"Rainbow Blade",
"Rainbow Wand",
"Raisin",
"Ramones T-Shirt",
"Rampage Spell",
"Rattle",
"Raze Spell",
"Recall Spell",
"Recipe Book",
"Record",
"Recovery Spell",
"Red Pill",
"Relic",
"Remember Spell",
"Repeating Bow",
"Return to Oz",
"Reznor Blade",
"Rig",
"Rivet",
"Roasted Garlic Clove",
"Roc Rock",
"Rock Salt Rock",
"Rodden Berry",
"Roll of Film",
"Ruby Bling",
"Ruby Slipper",
"Ruby Team Ring (Team Small Sand Worm)",
"Rusty Sword",
"S",
"Sacrificial Dagger",
"Sacrificial Sword",
"Safety Pin",
"Sai",
"Sallet",
"Saltpetre",
"Sazerac",
"Scrap of Vellum",
"Screen (The Earth City Flower Show)",
"Screen Printing Kit",
"Screwdriver",
"Seal Fur Coat",
"Seal Fur Stole",
"Seal Pelt",
"Seaweed Frond",
"Seaweed Surprise Ice Cream",
"Second-Aid Spell",
"Set of Steel Bars",
"Set of Water Wings",
"Sex Pistols T-Shirt",
"Sextant",
"Shaky Flake",
"Shanghorn Potion",
"Shark Fin",
"Shark Meat",
"Sharp Sword",
"Sheaf of Oats",
"Sheaf of Wheat",
"Sheep Eye",
"Sheep Heart",
"Sheep Lung",
"Sheep Stomach",
"Sheet of MDF",
"Sheet of Paper",
"Shell",
"Shield Spell",
"Shop Permit",
"Short Bow",
"Short String",
"Short Sword",
"Short Wool",
"Shredded Bus Ticket",
"Shredded Duck Bit",
"Shrimp Bow",
"Shrimp Catana",
"Shrimp Knife",
"Shrimp Stone",
"Shrimp Sword",
"Shrimp Sword2",
"Shrimp Talisman",
"Shrimp Wand",
"Shrimp Wand2",
"Shrimp Wand3",
"Sign Post",
"Silver Catana",
"Silver Knife",
"Silver Nail",
"Silver Ore",
"Silver Puzzle Box",
"Silver Rune",
"Silver Sword",
"Singing Sword",
"Single to Oz",
"Single to The 'Kingdom",
"Sisters of Mercy T-Shirt",
"Sixteenth of the Moon",
"Ski",
"Skip East Spell",
"Skip North Spell",
"Skip South Spell",
"Skip West Spell",
"Skull Gull Skull",
"Slice of Bacon",
"Slice of Bread",
"Slice of Crocodile Dundee Cake",
"Slice of Dundee Cake",
"Slice of Flying Bacon",
"Slice of Tomato",
"Slice of Wedding Cake",
"Sling",
"Slip Mat",
"Sloe Gin Fizz",
"Small Boat (in a bottle)",
"Small Magic Map",
"Small Map",
"Smiler Mask",
"Smite Spell",
"Snake Skin",
"Snowball",
"Snowman",
"Sod Spell",
"Solid Gold Fiddle",
"Sorting Office Pass",
"Soup",
"South-East Tunnel Map",
"South-East Tunnel Talisman",
"South-West Tunnel Map",
"South-West Tunnel Talisman",
"Space Rocket",
"Spade",
"Spade ov Kaos",
"Spare",
"Spartacus Mask",
"Spatula",
"Speaker",
"Speed Boat, unpowered (in a bottle)",
"Speedboat (in a bottle)",
"Speeder Bike",
"Speeder Bike, unpowered",
"Spikey Ninja Throwing Star",
"Spirit Bow",
"Spirit Catana",
"Spirit Catcher",
"Spirit Knife",
"Spirit Stone",
"Spirit Sword x 2",
"Spirit Sword2",
"Spirit Talisman",
"Spirit Wand",
"Spirit Wand2",
"Spirit Wand3",
"Spotter's Guide",
"Stall Permit",
"Stall Permit",
"Stall Permit",
"Stay on Target Spell",
"Stick of Butter",
"Stinger",
"Stone",
"Stone Egg",
"Strand of Silk",
"Strange Powder",
"Stranger in a Strange Land (Hardback)",
"Strength Spell",
"Strike",
"Sulphur",
"Summon Stone",
"Summon Stone (cracked)",
"Summon Stone X",
"Sun Flower",
"Sun Stone",
"Sun Stone Bling",
"Super Invisibility Spell",
"Survey Vessel (in a bottle)",
"Survey Vessel, unnavigable (in a bottle)",
"Sword of Omens",
"T",
"T-Shirt",
"T-Shirt (Dig My Grave Party)",
"T.G. Spell",
"Talisman (Golden Condor)",
"Talking Astrolabe",
"Tambourine",
"Tank",
"Tar",
"Tee",
"Teleport to Shop Spell",
"Tennis Ball",
"Tequila Slammer",
"Tequila Sunrise",
"The One Bling",
"The Way of the Finger",
"The art of Nasty Blows",
"The art of the Flaming Punch",
"The art of the Stone Fist",
"The art of the Wet Slap",
"Thick Skin Spell",
"Thieves' Talisman",
"Third-Aid Spell",
"Time Warp",
"Toad Spell",
"Toadvine Potion",
"Tom Collins",
"Toy Unicorn",
"Tray of Curry",
"Treasure Chest",
"Treasure Hunt List",
"Treasure Map (Tan Beards Treasure)",
"Trebuchet",
"Tri-Crow Bow",
"Triacle",
"Triangle",
"Tribble",
"Tribble Pelt",
"Triffid Sting",
"Trill Potion",
"Trout Mask",
"Trout Mask Replica",
"Tunnel Map",
"U",
"Umlaut",
"Uncertain Egg",
"Unicornucopia",
"Unit of Charcoal",
"Unit of Enchanted Charcoal",
"Unit of Sand",
"Unwrapped Gift",
"V",
"Vashka",
"Vault Permit",
"Vault Talisman",
"Venom Sac",
"Vertical Bling",
"Vial of Lanolin",
"Vial of Salad Dressing",
"Vial of Suncream",
"Viol",
"Vitality Spell",
"Vitsee Potion",
"Vodka Martini",
"Void Calling Spell",
"Vorpal Blade",
"Vowel",
"W",
"Wad of Raw Wool",
"Walking Stick",
"Wallbanger",
"Wand of Anger",
"Wand of Convincing Illusion",
"Wand of Illusion",
"Warrior's Totem",
"Watch Bling",
"Water Bomb Spell",
"Water Bow",
"Water Catana",
"Water Knife",
"Water Stone",
"Water Sword",
"Water Sword2",
"Water Talisman",
"Water Walking Spell",
"Water Wand",
"Water Wand2",
"Water Wand3",
"Wax Tablet",
"Wellbeing Spell",
"Whisker",
"Whisky Mac",
"White Egg",
"White Russian",
"White Sheet",
"Whole of the Moon",
"Winged Boot",
"Wire Fleece",
"Wizards Retreat Spell",
"Wombat Spell",
"Wool",
"Woolly Glove",
"Wormhole Entrance (Pink)",
"Wormhole Exit (Pink)",
"Wormhole Kit",
"Wyrm Spell",
"X",
"XX",
"XXXX",
"Y",
"Yellow Flower",
"Z",
"Zephyr Spell",
"Zombie");
}
</script>
</body></html>